// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuFXYEL-nyyBew7qdkwWYPfK2VOi9bx50',
    appId: '1:278910685584:web:01c9a488eae06b65a5e315',
    messagingSenderId: '278910685584',
    projectId: 'shebanks-mobile-app',
    authDomain: 'shebanks-mobile-app.firebaseapp.com',
    storageBucket: 'shebanks-mobile-app.appspot.com',
    measurementId: 'G-QL781RFG9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOZb1JZqao6pSbuFToPAgVlpvmeQWBeHg',
    appId: '1:278910685584:android:f4ceca9674a5e055a5e315',
    messagingSenderId: '278910685584',
    projectId: 'shebanks-mobile-app',
    storageBucket: 'shebanks-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjVxbn1grcVQiIHpssm6rQ1zztCSl9niA',
    appId: '1:278910685584:ios:4e20ea6de23f5c42a5e315',
    messagingSenderId: '278910685584',
    projectId: 'shebanks-mobile-app',
    storageBucket: 'shebanks-mobile-app.appspot.com',
    androidClientId: '278910685584-a6j33rptshbl83huo2souqqvdnnnnkor.apps.googleusercontent.com',
    iosClientId: '278910685584-of5rsf9b9rv009dml44mgddbqjmvn03g.apps.googleusercontent.com',
    iosBundleId: 'org.dotconnectafrica.shebnks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjVxbn1grcVQiIHpssm6rQ1zztCSl9niA',
    appId: '1:278910685584:ios:4e20ea6de23f5c42a5e315',
    messagingSenderId: '278910685584',
    projectId: 'shebanks-mobile-app',
    storageBucket: 'shebanks-mobile-app.appspot.com',
    androidClientId: '278910685584-a6j33rptshbl83huo2souqqvdnnnnkor.apps.googleusercontent.com',
    iosClientId: '278910685584-of5rsf9b9rv009dml44mgddbqjmvn03g.apps.googleusercontent.com',
    iosBundleId: 'org.dotconnectafrica.shebnks',
  );
}
