import 'dart:async';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_inapp_notifications/flutter_inapp_notifications.dart';
import 'package:flutter_phoenix/flutter_phoenix.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:mpesa_flutter_plugin/initializer.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:she_banks/api_services/api_services.dart';
import 'package:she_banks/models/loanModelCheck.dart';
import 'package:she_banks/models/loan_types.dart';
import 'package:she_banks/models/model_loan_status.dart';
import 'package:she_banks/models/model_user.dart';
import 'package:she_banks/screens/restart_widget.dart';
import 'package:she_banks/screens/screen_sheiq.dart';
import 'package:she_banks/screens/splash_screen.dart';
import 'package:she_banks/test.dart';
import 'package:she_banks/utils/NotificationProvider.dart';
import 'package:she_banks/utils/db_helper.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';
import '/firebase_options.dart'; // this file is generated by "flutterfire config" command

import 'firebase_options.dart';
final dbHelper = DatabaseHelper();

void main() async {
  MpesaFlutterPlugin.setConsumerKey("DP5PtSwqPSnfMK0mYK6XHjXEZ0Owallx");
  MpesaFlutterPlugin.setConsumerSecret("zOYjYZFvYXc10AZm");
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FirebaseMessaging messaging = FirebaseMessaging.instance;
  messaging.requestPermission();
  SharedPreferences _prefs = await SharedPreferences.getInstance();
  messaging.getToken().then((token) async {
    print('Device Token: $token');
    _prefs.setString('dToken', token!);

  });
  NotificationSettings settings = await messaging.requestPermission(
    alert: true,
    announcement: false,
    badge: true,
    carPlay: false,
    criticalAlert: false,
    provisional: false,
    sound: true,
  );
  print('User granted permission: ${settings.authorizationStatus}');

  // Lisitnening to the background messages

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    print('Got a message whilst in the foreground!');
    print('Message data: ${message.data}');

    if (message.notification != null) {
      print('Message also contained a notification: ${message.notification}');
    }
  });

  // FirebaseMessaging.onMessage.listen((RemoteMessage event) {
  //   print("message recieved");
  //   print(event.notification!.body);
  // });
  FirebaseMessaging.onMessageOpenedApp.listen((message) {
    print('Message clicked!');
  });
  runApp(
  MyApp());
      // ChangeNotifierProvider(
      //
      //   create: (context) => CheckLoan(),
      //   child: MyApp(),
      // ));
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return  MultiProvider(
        providers: [
        ChangeNotifierProvider(create: (context) => NotificationsProvider()),
    ],
    child:
        GetMaterialApp(
          title: 'Splash Screen',
          theme: ThemeData(
            textTheme: GoogleFonts.poppinsTextTheme(),
            useMaterial3: true,
            primarySwatch: Colors.green,
          ),
          home: SplashScreen(),
          builder: InAppNotifications.init(),
          debugShowCheckedModeBanner: false,
        ));
    //   ),
    // );
  }
}



Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print('Message Received');
}
